version: '3'
services:
  qwen-vl-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /workspace:/app  # Mount the RunPod persistent volume to your app
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]